Flesh out dev script a bit more

diff --git a/scripts/develop b/scripts/develop
--- a/scripts/develop
+++ b/scripts/develop
@@ -1,6 +1,26 @@
 #!/bin/bash
 
-cat <<EOF | kind create cluster --name polar --config=-
+enableHelmRepo() {
+  echo "Enabling Hashicorp Helm repo"
+  helm repo add hashicorp https://helm.releases.hashicorp.com 2>&1 > /dev/null
+}
+
+destroyCluster() {
+  local exists=$(kind get clusters | grep polar || true)
+  if [[ "$exists" != "polar" ]]; then
+    echo "Polar cluster not found"
+    exit 1
+  fi
+  kind delete cluster --name polar
+}
+
+createCluster() {
+  local exists=$(kind get clusters | grep polar || true)
+  if [[ "$exists" == "polar" ]]; then
+    echo "Polar cluster already exists"
+    exit 1
+  fi
+  cat <<EOF | kind create cluster --name polar --config=-
 kind: Cluster
 apiVersion: kind.x-k8s.io/v1alpha4
 nodes:
@@ -13,22 +33,21 @@ nodes:
         node-labels: "ingress-ready=true"
   extraPortMappings:
   - containerPort: 80
-    hostPort: 80
-    protocol: TCP
-  - containerPort: 443
-    hostPort: 443
+    hostPort: 8500
     protocol: TCP
 EOF
+}
 
-echo "Installing Gateway CRDs"
+installGatewayCRDs() {
+  echo "Installing Gateway CRDs"
+  kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=0fbc16ba7999bfb379f3c4fdcef589d7dd333e18" | kubectl apply -f -  2>&1 > /dev/null
+}
 
-kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=0fbc16ba7999bfb379f3c4fdcef589d7dd333e18" | kubectl apply -f -
+createServiceAccountForRBAC() {
+  echo "Creating Polar Service Account"
+  kubectl create serviceaccount polar 2>&1 > /dev/null
 
-echo "Creating Polar Service Account"
-
-kubectl create serviceaccount polar
-
-cat <<EOF | kubectl apply -f -
+  cat <<EOF | kubectl apply -f - 2>&1 > /dev/null
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
 metadata:
@@ -68,4 +87,191 @@ subjects:
   - kind: ServiceAccount
     name: polar
     namespace: default
+---
+apiVersion: rbac.authorization.k8s.io/v1
+kind: ClusterRoleBinding
+metadata:
+  name: consul-auth-binding
+  namespace: default
+roleRef:
+  apiGroup: rbac.authorization.k8s.io
+  kind: ClusterRole
+  name: polar-auth
+subjects:
+  - kind: ServiceAccount
+    name: consul-server
+    namespace: default
 EOF
+}
+
+createNginxIngress() {
+  echo "Creating nginx ingress"
+  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml 2>&1 > /dev/null
+  echo "Waiting for ingress pod to start"
+  sleep 10
+  kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
+}
+
+installConsul() {
+  echo "Installing consul helm chart"
+  cat <<EOF | helm install consul hashicorp/consul --version 0.32.0 -f - 2>&1 > /dev/null
+global:
+  name: consul
+server:
+  replicas: 1
+  extraConfig: |
+    {
+      "acl": {
+        "enabled": true,
+        "default_policy": "allow",
+        "enable_token_persistence": true
+      }
+    }
+ui:
+  enabled: true
+EOF
+  echo "Adding consul ui ingress"
+  cat <<EOF | kubectl apply -f - 2>&1 > /dev/null
+apiVersion: networking.k8s.io/v1
+kind: Ingress
+metadata:
+  name: consul-ingress
+spec:
+  ingressClassName: nginx
+  defaultBackend:
+    service:
+      name: consul-server
+      port:
+        number: 8500
+EOF
+  echo "Waiting for consul to stabilize"
+  sleep 10
+  kubectl wait --for=condition=ready pod --selector=app=consul,component=server,release=consul --timeout=90s
+  echo "Consul is now accessible at http://localhost:8500"
+}
+
+setupAuthMethod() {
+  local consul_policy=$(cat <<'EOF'
+node_prefix "" { policy = "write" }
+service_prefix "" { policy = "write" }
+agent_prefix "" { policy = "write" }
+event_prefix "" { policy = "write" }
+query_prefix "" { policy = "write" }
+session_prefix "" { policy = "write" }
+operator = "write"
+acl = "write"
+keyring = "write"
+EOF
+)
+  echo "Importing Kubernetes Configuration"
+  export K8S_JWT=$(kubectl get secret $(kubectl get serviceaccounts polar -o json | jq '.secrets[0].name' -r) -o json | jq '.data.token' -r | base64 -d)
+  export K8S_HOST=$(kind get kubeconfig --name polar --internal | grep server | tr -s ' '| cut -d' ' -f3)
+  export K8S_CERT=$(kubectl config view -o jsonpath='{.clusters[].cluster.certificate-authority-data}' --raw | base64 -d)
+  echo "Bootstrapping ACLs"
+  export CONSUL_HTTP_TOKEN=$(consul acl bootstrap -format json | jq '.SecretID' -r)
+  export CONSUL_POLICY_ID=$(consul acl policy create -name policy -rules "$consul_policy" -format json | jq '.ID' -r)
+  consul acl role create -name "polar" -policy-id "${CONSUL_POLICY_ID}" > /dev/null
+  echo "Creating ACL Auth Rule Binding"
+  consul acl auth-method create -type "kubernetes" -name "polar" -kubernetes-host "$K8S_HOST" -kubernetes-ca-cert "$K8S_CERT" -kubernetes-service-account-jwt "$K8S_JWT" | grep ServiceAccountJWT | cut -d':' -f 2 | tr -s " " | jq -r > token
+  consul acl binding-rule create -method=polar -bind-type=role -bind-name='polar' -selector='serviceaccount.name=="polar"' > /dev/null
+  echo $CONSUL_HTTP_TOKEN > token
+}
+
+buildPolar() {
+  echo "Cross-compiling polar for Linux"
+  GOOS=linux go build 2>&1 > /dev/null
+}
+
+buildDocker() {
+  echo "Building local docker container"
+  docker build . -t polar:1 2>&1 > /dev/null  
+}
+
+loadDockerImage() {
+  echo "Loading docker image into cluster"
+  kind load docker-image polar:1 polar:1 --name polar 2>&1 > /dev/null  
+}
+
+main() {
+  local destroy=$1
+  local provision=$2
+  local load=$3
+
+  if [[ "${destroy}" == "TRUE" ]]; then
+    destroyCluster
+  fi
+  if [[ "${provision}" == "TRUE" ]]; then
+    enableHelmRepo
+    createCluster
+    installGatewayCRDs
+    createServiceAccountForRBAC
+    createNginxIngress
+    installConsul
+    setupAuthMethod
+  fi
+  if [[ "${load}" == "TRUE" ]]; then
+    buildPolar
+    buildDocker
+    loadDockerImage
+    echo "To reload the init container after modifications run './scripts/develop -l'"
+  fi
+  if [[ "${start}" == "TRUE" ]]; then
+    export CONSUL_HTTP_TOKEN=$(cat token)
+    go build
+    ./polar server
+    echo "To re-run the server run './scripts/develop -s'"
+  fi
+}
+
+usage() {
+  echo -e "./scripts/develop [flags]"
+  echo -e "Dependencies:"
+  echo -e "\tkubectl, kind, consul, jq, docker, go, helm"
+  echo -e "Flags:"
+  echo -e "  -l\tRebuild and load docker container into cluster"
+  echo -e "  -d\tDestroy cluster"
+  echo -e "  -r\tDestroy and then remake cluster"
+  echo -e "  -h\tShow usage"
+  echo -e "  -s\tStart polar"
+}
+
+destroy=FALSE
+provision=TRUE
+load=TRUE
+start=TRUE
+
+while getopts drhls flag
+do
+    case "${flag}" in
+        d)
+          destroy=TRUE
+          provision=FALSE
+          load=FALSE
+          start=FALSE
+          ;;
+        r)
+          destroy=TRUE
+          provision=TRUE
+          load=TRUE
+          start=TRUE
+          ;;
+        h)
+          usage
+          exit 0 
+          ;;
+        l) 
+          load=TRUE
+          destroy=FALSE
+          provision=FALSE
+          start=FALSE
+          ;;
+        s) 
+          load=FALSE
+          destroy=FALSE
+          provision=FALSE
+          start=TRUE
+          ;;
+    esac
+done
+
+main $destroy $provision $load $start
